### PR TITLE
[rpm] Fix build by BuildRequires: pkgconfig(statefs)

### PR DESCRIPTION
**Pull request by tigeli**

### CODE REVIEW

**Comment by deztructor** [comment]
LGTM, if you checked it is built with this change :)

**Comment by monich** [comment]
Why would timed require statefs?

**Comment by deztructor** [comment]
@monich because it provides alarm indication info

**Comment by pgerdt** [comment]
@deztructor: was this issue caused by statefs pkconfig rename? Current timed spec file still has the following lines

BuildRequires:  pkgconfig(statefs-qt5)
BuildRequires:  statefs-devel >= 0.3.21

with which timed built just fine in the past.  I guess that the statefs changed and we have no need for those lines anymore (or at least we do not need to require statefs-qt5)?

**Comment by deztructor** [comment]
@pgerdt iirc, the change caused this issue is that statefs rpm macros is moved from statefs-devel to statefs-provider-devel - more logical place for it because clients do not use these macros. So, "BuildRequires: statefs-devel >= 0.3.21" is not needed anymore.

About pkgconfig(statefs-qt5): maybe it is used for the client part in the timed? Need to check the commit where it was introduced.

**Comment by pgerdt** [comment]
@deztructor: the commit is here: https://github.com/nemomobile/timed/commit/dacab81756e3fedf969e637cee9ca8cac0c063e7

AFAIK timed is not a statefs client, but it provides information.

**Comment by deztructor** [comment]
@pgerdt Thanks. So, it looks like only "Requires: statefs" and buildrequires from this commit is needed.

**Pull request merged**
